### ISSUE TITLE
qrCode nfce MG - infelizmente não está funcionando

### ISSUE THREAD

**Issue by marcelomresende** [ymoreiratiti/consultaNFE#16]
Olá pessoal, alguém consegue informar o que houve com a URL de consulta para Minas Gerais?

Já faz 2 meses que estou tentando implementar um sistema com ela e sempre retorna vazio.

exemplos:

https://nfce.fazenda.mg.gov.br/portalnfce/sistema/qrcode.xhtml?p=31210130887705000133650100000272401342688413|2|1|1|e1393ed145e8fa8d8d2129553b0267fa9001374b

http://nfce.fazenda.mg.gov.br/portalnfce/sistema/qrcode.xhtml?p=31200217745613001041650080000311271983498602|2|1|1|56fe7d60a407df2cb86db7e0d44464fbf0ff3491

**Comment by ymoreiratiti** [comment]
Buenas, Tranquilo & Sereno?

O primeiro link deu problema no certificado. pode existir algum erro relacionado a isso
https://nfce.fazenda.mg.gov.br/portalnfce/sistema/qrcode.xhtml?p=31210130887705000133650100000272401342688413|2|1|1|e1393ed145e8fa8d8d2129553b0267fa9001374b
![image](https://user-images.githubusercontent.com/5731429/114071086-196c7300-9877-11eb-9de8-24d05a8b7056.png)
Removendo o https:// ele até carrega a página, porem não existe nenhum dado, igual ao exemplo abaixo.

-----

Referente ao segundo link ele não trouxe os dados para essa nota
http://nfce.fazenda.mg.gov.br/portalnfce/sistema/qrcode.xhtml?p=31200217745613001041650080000311271983498602|2|1|1|56fe7d60a407df2cb86db7e0d44464fbf0ff3491
![image](https://user-images.githubusercontent.com/5731429/114071186-37d26e80-9877-11eb-9526-6c9a4a685ea0.png)

-----

Essas duas URLs foram retornadas pelo QRCode da NFCE?

**Comment by ymoreiratiti** [comment]
Encerrada por decurso de prazo
