### ISSUE TITLE
Error: Cannot find module './consulta'

### ISSUE THREAD

**Issue by olaviolacerda** [ymoreiratiti/consultaNFE#2]
Olá, pelo que entendi, na ultima vez que foi realizado o deploy aconteceu algo com o build e a pasta "consulta" não está presente na dist ocasionando esse problema ao executar o pacote. Acredito que uma nova tentativa de build e depois subir o pacote resolverá isso! Obrigado, qualquer coisa estou a disposição para ajudar.

**Comment by ymoreiratiti** [comment]
Buenas, Tranquilo & Sereno?


Sim, estava faltando o .npmignore


Lancei a versão 1.0.5:
- Atualização dos packages
- Alteração do endereço de consulta da Nota Fiscal RS (O endereço usava https, porem estão com problemas de certificado no site deles)
- Atualização da documentação
